### ISSUE TITLE
set output encoding in frontmatter

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/whiskers#7]
```yaml
whiskers:
  encoding: utf8-bom
  version: "2.1.0"
```

_originally posted by @nekowinston in https://github.com/catppuccin/toolbox/issues/179#issuecomment-2048375018_
