### ISSUE TITLE
add hex formatting options to frontmatter

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/whiskers#8]
it'd be nice to be able to configure how whiskers represents colour as hexadecimal.

for example, this template:

```yaml
---
whiskers:
  hex:
    capitalize: true
    prefix: "#"
---
{red.hex}
```

would produce `#D20F39` instead of the default `d20f39`.

`capitalize` + `prefix` as options gives us a good amount of flexibility out of the box for common formats like `#RRGGBB` and `0xRRGGBB`, but it's worth considering a more complex implementation that could allow more control, for example being able to specify a format string like `0x{a:02X}{b:02X}{g:02X}{r:02X}` to produce `0xAABBGGRR` format colours.
